### ISSUE TITLE
Run node command when yaml file change

### ISSUE THREAD

**Issue by lasithdilshan20** [Qard/onchange#100]
In my node project has a several yml files to get data. I need to execute js file when YML file change by the developer.

In my packege.json

`"scripts": {
    "start": "onchange '*.yml' '/cypress/testdata/convertor.js' -- node convertor.js"
  },`

seems like it's not working. Please help

**Comment by blakeembrey** [comment]
@lasithdilshan20 Can you share a way to replicate what you see. Based on this I wouldn't be able to help you.
