### ISSUE TITLE
Exclude is not working in 7.0.0

### ISSUE THREAD

**Issue by dnohr** [Qard/onchange#111]
Hi,

Thanks for working on this tool.

After upgrading to 7.0.0 I'm having issues with never-ending loops due to the exclude doesn't seem to be working anymore. Following code worked fine in all the previous versions:

`onchange 'public/js/*.js' -e '**/all.min.*' -- npm run build-js`

Maybe I couldn't spot it in the release notes, but anything I should change? For now, I rolled back to 6.1.1.

Thanks.

**Comment by blakeembrey** [comment]
My bad 🤕 I missed `exclude` in the args. Fixing now.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/Qard/onchange/releases/tag/v7.0.1

**Comment by dnohr** [comment]
I can confirm it's fixed in 7.0.1, thanks!
