### ISSUE TITLE
Multiple replacements failing

### ISSUE THREAD

**Issue by cjbarth** [Qard/onchange#116]
I have a npm script in `package.json` that looks like: `onchange 'src/**/*.ts' -- echo \"{{file}} changed...\" && echo \"{{file}} changed...\"`. The output from this command is only a single line: `myFile.ts changed...`. I expected to lines echoed to the prompt.

Are multiple replacements not supported or am I doing this wrong?

**Comment by Qard** [comment]
The command after the && would not be received by `onchange`, it's split out at the OS level. If you want to run multiple commands you'll need to put them in a bash script and pass the replacements in as arguments or use `bash -c "..."`.

**Comment by cjbarth** [comment]
I was trying to prevent multiple copies of `onchange` from running to handle both `prettier` and `eslint` in a cross-platform way. I'll close this issue and just run two copies of `onchange`, but I'm open to suggestions and can see value in a `README` update with such a suggestion too.

Thanks for your help.
