### ISSUE TITLE
Target multiple file extensions

### ISSUE THREAD

**Issue by rektide** [Qard/onchange#117]
Hello. We have a variety of code-bases & for convenience we've been running `onchange 'src/**/*.js' 'src/**/*.jsx' 'src/**/*.ts' 'src/**/*.tsx' -- our_command`.

It'd be nice to have some kind of syntax or option or something to not need to run a bunch of redundant watches like this. If there's an under the hood optimization that makes this ok, that'd be great, but my expectation is that there are redunant watches, and with our very large project tree, I'd love a less redundant way to watch good files while ignoring non-source files.

Perhaps more syntax? Syntax like `onchange 'src/**/*.{js,jsx,ts,tsx}'` might work. It could be fairly generic. But it might not be fun to implement.

It's a little more special case but a `--file-extension` option to filter things down with would also do the job: `onchange 'src/**/*' --file-extension js,jsx,ts,tsx`.

I could be willing to do some development here. Is there a preferred option, one that makes the most sense to do?

**Comment by Qard** [comment]
Path patterns are all handled by [picomatch](https://github.com/micromatch/picomatch) so any changes to the string would need to be made there.

**Comment by blakeembrey** [comment]
The patterns that @Qard mentions are the only ones supported. This requirement comes from [chokidar](https://github.com/paulmillr/chokidar) which is the underlying file watcher this library uses. We wouldn't be changing any supported patterns here directly, but you could open an issue against chokidar or picomatch with proposals that we can pull into this package. 

That said, it does look like `picomatch` has a supported way to do something like what you're after: https://github.com/micromatch/picomatch#extglobs.

Another alternative is that we build the glob support directly into this library, and manage the adding/removing of files from the watcher ourselves, but unfortunately that doesn't sound like fun to maintain in the long run. I'd consider a PR, but would recommend the other routes first.
