### ISSUE TITLE
Why it doesn't work in package.json scripts?

### ISSUE THREAD

**Issue by theajack** [Qard/onchange#119]
Onchange works with this cmd

`node .\node_modules\onchange\dist\bin.js -i '**' -- echo '{{event}} to {{file}}''`

![image](https://user-images.githubusercontent.com/23377279/129302559-05f149a4-7b76-45db-8c00-d1e2e9ffd44d.png)

But why it doesn't work in package.json scripts?

![image](https://user-images.githubusercontent.com/23377279/129302604-6db80887-fd82-47f4-aee8-6f88e8cdeef6.png)

![image](https://user-images.githubusercontent.com/23377279/129302651-1aec00b2-c8be-4dc7-ad09-be21b109e2e5.png)

**Comment by blakeembrey** [comment]
Do you have a reproduction I can use? I pretty much exclusively use this in package.json scripts so I’m not sure the error is in this module.

**Comment by theajack** [comment]
@blakeembrey Thanks for your reply, I found it might be because of the single quotes I used 😂

**Comment by blakeembrey** [comment]
Oh interesting, good catch. I don’t use windows often but it’d be because single quotes aren’t a quote character in windows shell. So in Unix the program would be seeing `**`, but windows was seeing `’**’`.

**Comment by blakeembrey** [comment]
I’m less familiar with the windows environment you screenshot compared to what environment shell scripts execute in. If you know feel free to comment and I can try adding the description to the README.
