### ISSUE TITLE
Multiple excludes

### ISSUE THREAD

**Issue by onetrev** [Qard/onchange#120]
Sorry if I'm missing something obvious, I tried this various ways with no luck. Is it possible to have multiple excludes, something like this:

```onchange '**/*.css' '**/*.js' -e 'folder/*.css' 'another-folder/*.js' -- npm run block-compile```

**Comment by blakeembrey** [comment]
` -e 'folder/*.css' -e 'another-folder/*.js'` - you're missing an extra argument flag.
