### ISSUE TITLE
What I want to do is execute some other script after the file has changed and "prettier" formatted

### ISSUE THREAD

**Issue by IceApriler** [Qard/onchange#127]
```bash
onchange \"src/**/*.js\" \"src/**/*.scss\" \"src/**/*.json\" -e \"{node_modules}\" -- prettier --write {{changed}} && echo 'echo some thing'
```
Hello, What I want to do is execute some other script after the file has changed and "prettier" formatted. What should I do?

**Comment by blakeembrey** [comment]
There's a similar answer here: https://github.com/Qard/onchange/issues/4#issuecomment-752642333. The approach is to basically write what you want as a shell script. You might also be able to use `-o` for this but I haven't tested it.
