### ISSUE TITLE
Execution on multiple files changed (e.g. branch switch)

### ISSUE THREAD

**Issue by MarMun** [Qard/onchange#129]
It executes for each file changed if multiple files change at once (think branch checkout).

I tried `-d` and `--await-write-finish` but that made no difference.

Maybe a throttle (or debounce?) option would be nice to prevent this.

**Comment by blakeembrey** [comment]
Can you elaborate on what you think the expected behavior is?

As far as I can understand this issue, I think it's working as expected. For every file changed, it's expected to run the command. Do you want it to run only once for files changed or something else?

**Comment by blakeembrey** [comment]
Maybe what you're describing wanting is more like a `--batch` option, that instead of running the task once per file change tries to batch them all up?

**Comment by MarMun** [comment]
Thanks for your reply @blakeembrey and sorry I didn't made clear what I meant.

If multiple files (e. g. 50) change at the same time (e. g. if I switch a branch), It doesn't make sense to run my task 50 times (one time would be enough as I run a build process).

I guess I like stuff to happen if there is

**any** change in the observed folder

and not

**for each** change in a given folder...

If this makes more sense. `-k` sounds like it is what I need. I'll try later and give feedback...

**Comment by MarMun** [comment]
`-k` does what I need. Thanks for your time (and the module!!). Best wishes.
