### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by shovon** [Qard/onchange#18]
I understand [`debug`](https://github.com/visionmedia/debug) is used for logging. But maybe we should have either

a. instructions on how to enable logging
b. *actually* display logging by default
c. anything that isn't going to confuse anyone

I'm about to make a pull request but not sure what would be the best thing.

What do you think, @Qard?

**Comment by Qard** [comment]
I think minimal noise is best for the tool. The DEBUG flag could be documented though.
