### ISSUE TITLE
Add flag to trigger first run

### ISSUE THREAD

**Issue by fatuhoku** [Qard/onchange#25]
Currently `onchange` only runs on when it detects a file change. However, onchange is incredibly useful when used as a part of a command line tool, and therefore should run at least once e.g. when firing up some unit tests.

**Comment by Qard** [comment]
You could also just do something like `npm test && onchange '*.js' -- npm test` rather than just `onchange '*.js' -- npm test`.

**Comment by blakeembrey** [comment]
@Qard I think this would be a pretty handy addition. I don't have a use-case that doesn't need this yet, so there's that.

**Comment by antoinerey** [comment]
`npm test && onchange '*.js' -- npm test` could work, but won't start the `onchange` part if the first `npm test` fails

**Comment by Qard** [comment]
Just replace the `&&` with `;` and it'll work, even if `npm test` fails.

I'm unlikely to have the time to do this anytime soon, but I'd be happy to accept a PR, if you want to write one.

**Comment by blakeembrey** [comment]
@Qard You can't use `;` on Windows though. The PR I made (https://github.com/Qard/onchange/pull/29) added this feature, but there's also a few other features. If it makes sense, I can put all the new changes behind flags to make it easier to merge.

**Comment by blakeembrey** [comment]
Released with https://github.com/Qard/onchange/releases/tag/v2.1.0
