### ISSUE TITLE
Multiple Glob Arguments Triggers the Command Twice

### ISSUE THREAD

**Issue by dacodekid** [Qard/onchange#27]
When supplying two or more glob patterns, noticed couple behaviors opposed to supply just one pattern.

1. The below code triggers ```npm test``` twice 
2. ```npm test``` runs immediately after I run ```npm start```

```json
  "scripts": {
    "test": "blue-tape test/*.js | tap-spec",
    "start": "onchange 'tasks/*.js' 'test/*.js' -- npm test"
  },
```
(But I'm not sure whether it is really triggers the ```npm test``` twice or displays the output twice. Because changing the command to ```"test": "clear && blue-tape test/*.js | tap-spec",``` doesn't ```clear``` the screen twice)

The below

```json
  "scripts": {
    "test": "blue-tape test/*.js | tap-spec",
    "start": "onchange '**/*.js' -- npm test"
  },
```
waits for some file change on ```npm start``` and runs ```npm test``` just once. 

Am I doing something wrong here?

This is my output in question
```
> blog@0.1.0 test /Users/dacodekid/dev/testapp
> blue-tape test/*.js | tap-spec


> blog@0.1.0 test /Users/dacodekid/dev/testapp
> blue-tape test/*.js | tap-spec


  basic arithmetic

    ✔ should be equal
    ✔ should be equal

  basic arithmetic


    ✔ should be equal
    ✔ should be equal

  total:     2
  passing:   2
  duration:  11ms


▀ 
  total:     2
  passing:   2
  duration:  11ms
```

**Comment by Qard** [comment]
Not sure why it'd be doing that. I'll have a look tomorrow.

**Comment by dacodekid** [comment]
@Qard, thx but now it doesn't look like it is ```onchange```'s behavior. I just changed my tests from ```tape``` to ```mocha - chai``` and the same ```onchange``` command works as it should. This could be either ```tape / blue-tape``` issue (even after removing ```tap-desc``` reporter, got the same double output - that could be the reason why the clear command didn't run twice).

If you could confirm that this is not ```onchange``` issue, plz close this ticket.

```json
    "test": "mocha",
    "start":"onchange './tasks/*.js' './test/*.js' -- npm test"
```

Mocha Output

```
> blog@0.1.0 test /Users/dacodekid/dev/testapp
> mocha



  test
    ✓ testing


  1 passing (8ms)
```
