### ISSUE TITLE
Long running processes

### ISSUE THREAD

**Issue by blakeembrey** [Qard/onchange#28]
Thoughts on supporting long running processes? Reason: I'd love to continue using `onchange` but I want to use it for a slightly different use-case. In this case, I need to combine it with an initial flag and if it's running on reload kill the current process and spawn a new one. 

If it seems reasonable, I can definitely open a PR. I can also make it throttle changes with this implementation.

**Comment by Qard** [comment]
That seems more like a hot-reloading tool. That's not really what this is meant for.

Can you elaborate more on why you'd want to use this particular tool for something like that, versus something like [recluster](https://www.npmjs.com/package/recluster) or [herd](https://www.npmjs.com/package/herd)?

**Comment by blakeembrey** [comment]
I'm just after a simple CLI that will reload on change, I don't need a specific tool for clustering or hot code reloading. Right now I use `nodemon`, but the functionality is pretty much equivalent to what this library already does. Figured it'd be easier to kill two birds with one stone - make reloads while already running work and add initial run support, then my use-case is already working.
