### ISSUE TITLE
Multiple changes trigger onchange in parallel.

### ISSUE THREAD

**Issue by unional** [Qard/onchange#31]
Or until the triggered command completes, don't fire the the command again.

Use case:
Quickly make changes to several files.

Result:
Multiple build+test has been triggered at close interval, most of the time before the previous command(s) complete.

**Comment by Qard** [comment]
It's probably better to cancel and restart in that sort of situation. Processing for the later changed files may have already occurred before they were saved, then you have a result that is perhaps not what is expected.

**Comment by unional** [comment]
That would be nice.

**Comment by blakeembrey** [comment]
Thanks for the report, theoretically this should already be happening but let me recreate some tests and make sure.

**Comment by blakeembrey** [comment]
@unional I can't seem to replicate it, the way the current code works is that it attempts to close the current process but it won't start a new process until the current one closes. Are you seeing this not happening and can you share where?

![image](https://cloud.githubusercontent.com/assets/1088987/14219308/719669b4-f80e-11e5-84e2-aac67a41947c.png)

In that example it was all invalid but only when I slowed enough did it actually execute long enough to print compilation errors.

**Comment by unional** [comment]
Typings projects with test might able to reproduce it easier. See `typed-iscroll`. I'm out for lunch so don't have computer to get output

**Comment by blakeembrey** [comment]
Perhaps using `exit` instead of `close` events might improve this? Would you want to test it using `exit` events instead of `close` and see how that goes?

**Comment by unional** [comment]
Ok

**Comment by unional** [comment]
I tried in my code and it did trigger multiple times.
The script 
{
  "scripts": {
    "watch": "onchange \"**/*.ts\" -e \"**/*.d.ts\" -i -- npm run -s lint+test",
    "lint+test": "npm run lint && npm test",
  }
}
```

When I making changes multiple times (just add space, save, and repeats), it prints out:
```sh                
linting...       
linting...       
testing...       
linting...       
linting...       
testing...       
testing...       

# then multiple test results printed
```

**Comment by unional** [comment]
When I try with `exit`, it throws with this:
```sh
npm ERR! Please include the following file with any support request:
npm ERR!     E:\hwong\bitbucket\pandash\npm-debug.log
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write

npm ERR! write EPIPE
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\hwong\bitbucket\pandash\npm-debug.log
```
I tried to both:
- https://github.com/Qard/onchange/blob/master/index.js#L55 to `exit`
- and/or https://github.com/Qard/onchange/blob/master/index.js#L37 and https://github.com/Qard/onchange/blob/master/index.js#L29 to `exit`

**Comment by blakeembrey** [comment]
Thanks @unional! I'm going to get some tests up and running this week and resolve it properly.

**Comment by blakeembrey** [comment]
@unional I can't handle NPM scripts properly, it seems that it doesn't wait for the child to exit. I'll find an issue related to this, I recall it somewhere, but I'm not sure there's much that can be done beyond this. The kill behaviour is kind of nice, maybe I can make a flag to instead enable the wait to re-run behaviour I've also implemented.

**Comment by blakeembrey** [comment]
@unional See this issue: https://github.com/kimmobrunfeldt/concurrently/issues/4.

**Comment by blakeembrey** [comment]
@unional You may be interested in https://github.com/Qard/onchange/releases/tag/v2.3.0 until the NPM changes. If you pass `-w`, it'll wait for the current process to finish before restarting so you don't run multiple in parallel.

**Comment by unional** [comment]
Thank, as always! :smile:

From this:
https://github.com/kimmobrunfeldt/concurrently/issues/4#issuecomment-205964746
Does this mean it is fixed in npm 3.8.1?

**Comment by blakeembrey** [comment]
It would appear so. So child processes should properly exit after 3.8.1. If it doesn't, you can at least use the new `-w` option.

**Comment by unional** [comment]
Confirmed that `-w` works but npm 3.8.1 changes doesn't. :+1:
