### ISSUE TITLE
Idea: --once flag 

### ISSUE THREAD

**Issue by thefabulousdev** [Qard/onchange#34]
Would be cool to have a `--once` flag which would execute the given command on change only once, this could also be implemented as `--times x`  where `--once` is just an alias for `--times 1`, this is useful for bootstrap tasks that rely on foreign tasks to create/update bootstrap configuration.

**Comment by blakeembrey** [comment]
Can you give an example or elaborate more? Technically tasks currently run once on change, do you perhaps mean something more like a timeout?

**Comment by thefabulousdev** [comment]
Rephrasing: Would be cool to be able to limit the amount of times a script can be executed, for example 
```bash
onchange myfile.json --times 2 -- npm run iwillhappentwice
```
and to perhaps have an alias for `--times 1` like 
```bash
onchange myfile.json --once -- npm run ionlyhappenonce
```

After the scripts have been run the specified amount of times, the process exits

**Comment by thefabulousdev** [comment]
I do not mean, every time `myfile.json` changes the script will hapen once or twice on the previous examples, but the file change will be listened once or twice

**Comment by blakeembrey** [comment]
Can you write an example use-case? I think that would make the most sense. I'm still not quite understanding, sorry. I mean, I think I understand the how, just not the why.

**Comment by thefabulousdev** [comment]
After giving it a thought, every usecase I might give is a product of a bad implementation of a build process. Closing issue.
