### ISSUE TITLE
onchange fire by itself (ts-node related)

### ISSUE THREAD

**Issue by unional** [Qard/onchange#36]
I use `onchange` in npm script to watch file changes to re-run tests.

I notice for some reason `onchange` has detect changes out of nowhere and keep rerunning the tests

I look at the files and notice `.git/FETCH_HEAD` is updating continuously. I believe it is done by VSCode.

However, my `onchange` call does not listen to the `.git` folder (of course).
My call is `onchange -w -i \"src/**/*.ts\ -- npm run test-spec`

I tried to exclude the folder `onchange -w -i \"src/**/*.ts\" -e \"**/.DS_Store\" -e \".git/*\" -- npm run test-spec` but it still keep running by itself. So FETCH_HEAD may not be the cause.

You can see / try the call here: https://github.com/typings/core/tree/add-jspm

Don't know if it would be reproducible.

**Comment by unional** [comment]
I look into it further and somehow it seems like it is actually `ts-node` related. If I don't run the tests, `onchange` doesn't fire again. 

To complete the story:

```js
// package.json
{
  "scripts": {
    "test-spec": "ts-node node_modules/blue-tape/bin/blue-tape.js \"src/**/*.spec.ts\" | tap-diff",
    "watch": "onchange -w -i \"src/**/*.ts\" -- npm run test-spec"
    // ...
  }
}
```

If I run `onchange -w -i \"src/**/*.ts\" -- echo "running"`, it does not fire again.
If I run `onchange -w -i \"src/**/*.ts\" -- ts-node node_modules/blue-tape/bin/blue-tape.js \"src/**/*.spec.ts\"`, it does.

**Comment by unional** [comment]
Is there a way to combine the test running and `-- echo '{{event}} to {{changed}}'` to show what has happened?

By the way, I don't know how the `{{event}} to {{changed}}` works.

**Comment by Qard** [comment]
`{{event}}` and `{{changed}}` are templates that get replaced anywhere in the command after the `--`. You could try something like `/bin/sh -c "echo '{{event}} to {{changed}}' && my-command"` to combine two commands. You'll have to make sure you escape the double quotes properly, if you put that in your package.json file.

**Comment by unional** [comment]
Thank! That's really helpful.

I discovered the issue is within the project test cases themselves.

**Comment by Qard** [comment]
Great, glad you worked it out. 😸
