### ISSUE TITLE
Doesn't watch files in node_modules directory

### ISSUE THREAD

**Issue by ssylvia** [Qard/onchange#39]
Have the following npm script:
```js
onchange './config/**/*.js' './config/scripts/docs/docs-readme.md' './src/**/*.js' './node_modules/my-shared-components/src/**/*.js' -- npm run docs:build
```

It seems to work on everything but the last node_modules path

**Comment by blakeembrey** [comment]
That is intentional, see https://github.com/Qard/onchange/blob/master/cli.js#L32-L35.

**Comment by ssylvia** [comment]
No way to add an exception if I point to a specific directory?

**Comment by blakeembrey** [comment]
Sure, it can be changed so that you can do `--no-exclude` or something similar. Feel free to submit a PR.
