### ISSUE TITLE
How do I pass multiple commands with && or alternative?

### ISSUE THREAD

**Issue by reggi** [Qard/onchange#4]
**_This Works_**

I can pass a command to send a notification when the file is changed. 

```
onchange ./components/breaknotes.yml -- terminal-notifier -message 'breaknotes updated'
```

**_This doesn't work_**

I'm trying to run two commands `cd` and `terminal-notifier` with a `&&` in between and it's not working

```
onchange ./components/breaknotes.yml -- cd ./generators/ && terminal-notifier -message 'breaknotes updated'
```

**_This Works_**

I can run this in the terminal no problem and it works.

```
cd ./generators/ && terminal-notifier -message 'breaknotes updated'
```

How do I pass multiple commands to run when a file is saved?

**_Update_**

Got it to work like this:

```
    "update:breaknotes": "cd ./generators/ && node component.js breaknotes && terminal-notifier -message 'breaknotes updated'",
    "watch:breaknotes": "onchange ./components/breaknotes.yml -- npm run update:breaknotes"
```

Still curious to how I'd get it to work on one line.

**Comment by Qard** [comment]
Doing `npm run change-happened` seems good enough for me. I'm closing this, as I'm not going to bother adding something like this myself. I'm open to PRs though, if the method seems reasonable.

**Comment by exalted** [comment]
Something like this could work: `onchange ./components/breaknotes.yml -- sh -c 'cd ./generators/ && terminal-notifier -message "breaknotes updated"'`

**Comment by miclgael** [comment]
exalted's method worked for me 🙏
