### ISSUE TITLE
Allow usePolling option in chokidar to handle nfs mounts

### ISSUE THREAD

**Issue by redheadedstep** [Qard/onchange#40]
Basically, I code to a local directory on Mac OS X that is exported/mounted into a Debian VM via NFS.  Right now, if I change a file in OS X, nothing is triggered to chokidar (and subsequently to onchange).  If I touch the file within the VM or edit it within the VM, it is triggered and passed through to onchange.

From what I can tell, onchange uses chokidar(https://github.com/paulmillr/chokidar) which uses watchify(https://github.com/substack/watchify) to actually watch the files.  

There was an issue on watchify about watching files on an nfs mount:

[**Changes to files on NFS should be detected**](https://github.com/substack/watchify/issues/120)

Watchify and Chokidar have already fixed this problem (https://github.com/substack/watchify/issues/120) by enabling polling instead of using FSEvents.  Now I just need a way to pass this option into chokidar from onchange.

Is there a way to enable polling on chokidar through an option in onchange?

**Comment by blakeembrey** [comment]
Watchify isn't related to chokidar, in fact, it uses chokidar. However, there's no option currently in `onchange`. You can use the environment variable specified in https://github.com/paulmillr/chokidar#performance until it does exist. I'd be happy to accept a PR that mirrors the CLI options added in watchify to here.

**Comment by redheadedstep** [comment]
Thanks for the quick response.  I hadn't seen that env variable earlier.

I was able to get on change to work from what I originally had in package.json:

`
{
  "watch": "onchange src/ -i -v -- npm test -s"
}
`

changed to:

`
{
  "watch": "CHOKIDAR_USEPOLLING=true onchange src/ -i -v -- npm test -s"
}
`

It takes an extra few seconds to find the files (probably from the polling), but it's better than having to `touch` each file that changes.
