### ISSUE TITLE
Watch option broken in 3.1.0

### ISSUE THREAD

**Issue by marco-eckstein** [Qard/onchange#45]
Starting from 3.1.0, the watch option (-w, --watch) is broken. Processes are killed. 3.0.2 is still good.

**Comment by blakeembrey** [comment]
Thanks for the catch, it looks like I've accidentally shadowed the options I was using from the global function. Pushing a patch now. Just FYI, it's `--wait` too - see https://github.com/Qard/onchange#wait--w---wait

**Comment by blakeembrey** [comment]
Fixed in https://github.com/Qard/onchange/releases/tag/v3.2.1. Was previously broken by https://github.com/Qard/onchange/commit/8762f157db42985df2164949702e3f5640c41b0d. Thanks again!

**Comment by marco-eckstein** [comment]
Thanks for the quick fix! I will check it out next week when I am back to work. I have edited the title and description, because I was incorrectly referring to the "watch" option instead of "wait".
