### ISSUE TITLE
Detect changes at any depth based on glob pattern

### ISSUE THREAD

**Issue by joncursi** [Qard/onchange#47]
Is there a way to tell onchange to run for a `.js` file at any depth beneath some `src/` folder?

Right now, running:

```
onchange src/**/*.js
```

only re-runs for files two levels deep, i.e. `src/someFolder/file.js` , but will not run for `src/file.js` or `src/someFolder/anotherFolder/file.js`.

I suppose this would work:

```
onchange 'src/*.js' 'src/**/*.js' 'src/**/**/*.js'
```

But that is a silly solution to the problem that would have to be updated every time a new level is introduced under `src/`. Thoughts?

**Comment by blakeembrey** [comment]
This is should be how it works today, but because you aren't using quotes the files are probably being expanded by your shell and not `onchange`. Try putting your glob in quotes.

**Comment by joncursi** [comment]
@blakeembrey you the man! 🎉

**Comment by blakeembrey** [comment]
@joncursi Thanks, it's the type of thing that gets everyone the first time 😄
