### ISSUE TITLE
Ability to clear before running command

### ISSUE THREAD

**Issue by joncursi** [Qard/onchange#48]
The following does not work unfortunately:

```
onchange \"**/*.js\" -i -- clear && yarn test
```

After the console clears, it just hangs there and never gets to the test command.

**Comment by joncursi** [comment]
FWIW, using `npm-run-all` solves this if you create a `clear` task that simply clears:

```
onchange \"**/*.js\" -i -- npm-run-all clear test
```

**Comment by blakeembrey** [comment]
That's expected, this is still a regular shell so you wrote `&&` after `onchange` finishes, which it would never by design. You could put that command into any single npm script and it would work. You could also use the `--outpipe` option introduced from https://github.com/Qard/onchange/issues/37.

**Comment by devinrhode2** [comment]
If you are doing something other than `yarn test` - perhaps where you are executing a .js file with node, you may want to clear console at the top of that .js file with this code:

```
// clear console by printing page of newlines. So you can scroll up if you want.
const readline = require('readline');
const blank = '\n'.repeat(process.stdout.rows);
console.log(blank);
readline.cursorTo(process.stdout, 0, 0);
readline.clearScreenDown(process.stdout);
```

**Comment by blakeembrey** [comment]
@devinrhode2 I'd be happy to incorporate that code into this module first-class. It sounds useful to have. Could either have a `--before` flag in the CLI for a command to run first (e.g. opposite of `--outpipe` which would clear afterwards) and you could use it with something like https://www.npmjs.com/package/cli-clear, or make a specify `--clear` flag.

**Comment by devinrhode2** [comment]
Feel free to drop it in. It would be nicer than what I have now. What I have now will "clear" my npm script command, so developers cant see what files are being watched

Before my clearing stuff it'd print:
```
projA ➤ npm start                                                                                                                                                    git:dev

> create-projA@0.1.0 start /Users/dr2/repos/projA
> onchange --initial --kill "src/setupProxy.js" "package.json" "dev-scripts/craco.config.js" -- craco start

** craco.config.js successfully loaded **
# Continue running dev server
```

Now all we see is: 
```

** craco.config.js successfully loaded **
# Continue running dev server
```
Therefore developers dont get to see whats going on. with our `npm start` script.
