### ISSUE TITLE
Using changed file name or path in script

### ISSUE THREAD

**Issue by reggi** [Qard/onchange#5]
I don't know if this exists already but it would be really nice to be able to pipe in the name of the file changed to the command that runs.

Like this:

```
onchange ./components/* -- npm run update -- $changed_file
```

**Comment by JakeGinnivan** [comment]
This would be great.

**Comment by reggi** [comment]
This is already possible with `xargs` I got deep here's a good starting point 

http://unix.stackexchange.com/a/173846/11440
https://github.com/keithamus/npm-scripts-example/issues/4#issuecomment-66808338

**Comment by Qard** [comment]
This is possible in 1.0.0 by using `{{changed}}` anywhere in the command after `--`.

**Comment by reggi** [comment]
:clap:
