### ISSUE TITLE
Saving multiple files (File > Save all) triggers onchange only once or twice

### ISSUE THREAD

**Issue by jnachtigall** [Qard/onchange#56]
FWIW, I left a (now closed) report at https://github.com/prettier/prettier/issues/3264

On Windows 10 with VSCode and git bash I am seeing this:
Change 3 files and "Save all", this happens:

```
$ node_modules/.bin/onchange -w "*.js" "tasks/**/*.js"  -- echo 'This here has changed:' {{changed}}
This here has changed: tasks\register\build.js
This here has changed: tasks\config\eslint.js
```

FWIW, I also changed a 3rd file `tasks\config\clean.js` which does not get fired.

**Comment by blakeembrey** [comment]
It may be better to look into chokidar. All events are provided by the underlying path watcher. I'll also check for some updates on this side.

**Comment by felixfbecker** [comment]
I think this is a bug in `onchange`. When using `-v`, I can see that `onchange` noticed that `foo.js` changed, but it only executed the command for `foo.d.ts`:
```
> onchange 'lib/**/*' -v -w -- cp -v -r '{{changed}}' "test/{{changed}}"
onchange: watching lib/**/*
onchange: change to lib/foo.js.map
onchange: executing command "cp -v -r lib/foo.js.map test/lib/foo.js.map"
onchange: change to lib/foo.js
onchange: waiting for process and restarting
onchange: change to lib/foo.d.ts
lib/foo.js.map -> /Users/felix/git/sourcegraph/browser-extension/node_modules/@sourcegraph/codeintellify/lib/foo.js.map
```
Same issue without `-w`:

```
> onchange 'lib/**/*' -v -- cp -v -r '{{changed}}' "test/{{changed}}"
onchange: watching lib/**/*
onchange: change to lib/foo.js.map
onchange: executing command "cp -v -r lib/foo.js.map /Users/felix/test/lib/foo.js.map"
onchange: change to lib/foo.js
onchange: killing command 97708 and restarting
lib/foo.js.map -> /Users/felix/test/lib/foo.js.map
```
Note how the command was never executed for `foo.js`, only `foo.js.map`.

**Comment by blakeembrey** [comment]
@felixfbecker Thanks for the example! I think I understand the issue better now. It might be related to the lack of queuing internally - only one subprocess is expected to run at the same time. I'll think about how to improve this as it certainly would be an issue in your case. What do you feel is the expected behaviour - do we spawn multiple subprocesses at the same time (e.g. new flag `-c`) or create an internal queue so everything executes without dropping steps?

**Comment by felixfbecker** [comment]
In my case, handling events concurrently is fine, but it doesn't really matter as the command I want to run is fast. It would just need to make sure logs don't get mangled.

**Comment by Dhq** [comment]
I know this is closed, but is there a way to get the old behaviour back? I am interested in only triggering the event once even if multiple files change at (almost) the same time. Like some kind of debounce functionality.  @blakeembrey

**Comment by Dhq** [comment]
Ah, the `-k` flag does what I wanted. Never mind :)
