### ISSUE TITLE
Running "git diff" on a file causes onChange to think the file was changed

### ISSUE THREAD

**Issue by milesrichardson** [Qard/onchange#57]
Simple usage of `onChange`:

``` bash
"$FF_DIR"/node_modules/.bin/onchange 'src/libcommon/**/*.js' 'src/server/**/*.js' 'src/server/**/*.json' -v -i -- "$DIR/dev_build_run_server.sh"
```

Then I run:

``` bash
git diff */parseConstraints.js
```
(also happens running like this):

``` bash
git diff src/server/parse/cloud/helpers/parseConstraints.js
```

verbose log then says:

``` bash
onchange: change to src/server/parse/cloud/helpers/parseConstraints.js
```

Perhaps this is not a bug, and `git diff` actually modifies the file somehow? I searched around google for `git diff` modifying files and couldn't find anything.

Note that after running `git diff`, `ls` shows the modification time has NOT changed.

It's a simple thing to test. Would appreciate if anyone could reproduce, or if something is wrong with my git.

**Comment by blakeembrey** [comment]
This module is a small wrapper around the large body of work in `chokidar`. I'd considering searching for or logging an issue with them, unfortunately there's not a ton of support for file-system issues here 😄 

Reference: https://github.com/Qard/onchange/blob/73c96a8d4414dfd839b6d94863eee0d572533b14/index.js#L5
