### ISSUE TITLE
error when no command passed argument

### ISSUE THREAD

**Issue by reggi** [Qard/onchange#6]
```bash
thomas@workstation:figaro-plus$ onchange ./components/*
FATAL ERROR: JS Allocation failed - process out of memory
```

so i have to do something silly like

```bash
onchange ./components/* -- false
```

**Comment by Qard** [comment]
With 1.0.0, you can simply do `onchange '*.ext' -- echo "{{changed}}" | other-script` to get a stream of filenames as changes occur. Does that work for what you need?

**Comment by blakeembrey** [comment]
Released with https://github.com/Qard/onchange/releases/tag/v2.1.0
