### ISSUE TITLE
Can we show timestamp after triggering an action

### ISSUE THREAD

**Issue by wangbourne** [Qard/onchange#61]
In practice, I hope I can see the timestamp, so I will be confident that it is indeed triggered. Thanks

**Comment by gurumojo** [comment]
Enjoying this lib. Thanks to the maintainers!

I liked the sound of this request and gave my +1, imagining a `Timestamp (-t, --timestamp)` echo option.

... went searching and found https://github.com/Qard/onchange/issues/9 with guidance to add the equivalent of `date +%s` to a change script.

**Comment by blakeembrey** [comment]
@wangbourne What exactly would you like to see? I'm taking a guess, but is this only for verbose mode logging?

**Comment by blakeembrey** [comment]
Closing without any response. Feel free to use the script to emit the date.
