### ISSUE TITLE
Onchange doesn't recognize the "--poll" flag

### ISSUE THREAD

**Issue by mikolajzieba** [Qard/onchange#68]
When tryingto run nochange with a "--pool" or "-p" flag, I get an error.

`onchange -p '**/*.js' -- npm test`
Error:
`Usage: onchange [...file] -- <command> [...args]`

`+ onchange@5.0.0`

**Comment by blakeembrey** [comment]
Thanks. This is probably a limitation of the CLI parser actually. I didn’t think of it when I wrote it, but it probably can’t support boolean and number in the same argument. Can you try with an poll interval number for now and I’ll update the documentation?

**Comment by blakeembrey** [comment]
Clarified documentation in https://github.com/Qard/onchange/commit/7b5c03806eab4fce89b4e30413ad310e44987977.
