### ISSUE TITLE
Onchange does not detect changes when used in a directory with parenthesis

### ISSUE THREAD

**Issue by benjrichardson** [Qard/onchange#70]
To reproduce, create a directory with parenthesis in the name. For example, testdir(2). Then run a command like:

`onchange "**/*.scss" -- echo "{{event}} to {{changed}}"`

Onchange then fails to recognize any changes made to any files in the directory. It also seems to happen in any subfolders, for example if I run onchange in something like testdir(2)/foo/whatever.

**Comment by blakeembrey** [comment]
This seems like it'd be an issue with `chokidar`, which is the library we use to watch for file changes: https://github.com/paulmillr/chokidar

**Comment by blakeembrey** [comment]
Closing and leaving it up to chokidar to resolve.
