### ISSUE TITLE
Configure threshold time of "--await-write-finish"

### ISSUE THREAD

**Issue by p-vogt** [Qard/onchange#71]
Hi, thanks for this nice package.

I'd like to configure the "threshold time" of `--await-write-finish`, as stated in the readme:

> Await Write Finish (--await-write-finish)
> To hold the events until the size does not change for a **configurable amount of time**

Is this really possible? If so, how? 

I just got it working by adjusting chokidar's `stabilityThreshold` directly in the code:

```
...
// Create the "watcher" instance for file system changes.
const watcher = chokidar.watch(matches, {
  cwd: cwd,
  ignored: opts.exclude || [],
  usePolling: opts.poll === true || typeof opts.poll === 'number',
  interval: typeof opts.poll === 'number' ? opts.poll : undefined,
  awaitWriteFinish: { stabilityThreshold: ..., pollInterval: ... } // <---------
})
...
```

**Comment by blakeembrey** [comment]
The original PR is https://github.com/Qard/onchange/pull/66. It looks like the message is incorrect. You're welcome to submit a PR to add this functionality.
