### ISSUE TITLE
Changes not being triggered on Docker

### ISSUE THREAD

**Issue by theprobugmaker** [Qard/onchange#79]
I have this simple setup for testing purposes:

`Dockerfile`:
```docker
FROM node:11.2.0-alpine
WORKDIR /usr/src/app
RUN yarn
```

`docker-compose.yml`:
```docker
version: "3.7"
services:
  server:
    build: .
    command: yarn start
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
```

`index.js`:
```js
const express = require("express");

const app = express();

app.get("/", (req, res) => {
  res.send("hello world");
});

app.listen(4000, () => console.log("The server is listening on port 4000"));
```

In  my `package.json` I have a script that is:

```
"scripts": {
  "start": "onchange -i -k **/*.js -- node index.js"
}
```

It does work locally in my computer, however when running in a Docker container it doesn't detect the changes and nothing happens.

**Comment by blakeembrey** [comment]
@zefexdeveloper So the file watcher is chokidar. I didn't find much on Docker, but I did find https://github.com/paulmillr/chokidar/issues/590. Have you had any luck with chokidar directly or any other file watchers for node.js?

**Comment by zefexdeveloper** [comment]
@blakeembrey I haven't tried chokidar directly on docker to be honest. I was using `nodemon` with the legeacy watcher but I'm having a lot of problems with it and for that reason I'm looking for an alternative, I tried to use `onchange` (hoping it would work) but for some reason it doesn't.

**Comment by blakeembrey** [comment]
@zefexdeveloper Can you try https://github.com/Qard/onchange#poll--p-ms---poll-ms as a workaround for now? It might be an issue with the mounted directory in Docker so polling would be a workaround (I know Windows mounted partitions have a similar issue).

**Comment by zefexdeveloper** [comment]
@zefexdeveloper It's having the same problem as I was having with `nodemon`, it seems to not be closing the process and trying to open another one.

> Error: listen EADDRINUSE: address already in use :::4000

https://github.com/remy/nodemon/issues/1477

**Comment by blakeembrey** [comment]
@zefexdeveloper You're saying it isn't closing the previous process before starting a new process? That seems odd since it listens for `exit` on the process before spawning another, but I'll have to give it a go to replicate. Do you have a simple repo with the above configuration to get started there? I can do it myself too, but it may take a bit longer to get around to is all 😄

**Comment by zefexdeveloper** [comment]
@blakeembrey Yes, it's really weird, but it's like opening a new process and that is why it's saying that the port is already in use.
I don't have a repo with the configuration I sent, I can do that later (it's 4AM for me right now), or you can try in the mean time. (if possible)

**Comment by zefexdeveloper** [comment]
@blakeembrey It was fixed in `nodemon`, the problem `ps tree` a module based on `node-kill-tree`, the same module you are using. That is how it was fixed:

https://github.com/remy/pstree/commit/5f58daf1e13038b279d6e79e608040eb5e07a36e
