### ISSUE TITLE
ENOENT when running npm scripts

### ISSUE THREAD

**Issue by mattecapu** [Qard/onchange#8]
This command
```
onchange foo.css -- npm run bar
```
Fails regardlessly of what `bar` do.
This is the error it raises:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```
I'm experiencing this only when trying to execute an `npm` script, the same command passed directly to `onchange` works fine. I'm running Windows 8.1.

**Comment by Qard** [comment]
Weird. It works fine in Linux and OSX. I'll have to see if I can find a Windows box to do some testing on.

**Comment by JakeGinnivan** [comment]
I get the same thing when trying to run jshint.

```
> onchange foo.js -- jshint foo.js

watching foo.js
changed \foo.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

npm ERR! foo@1.0.0 watch-jshint: `onchange foo.js -- jshint foo.js`
npm ERR! Exit status 8
```

**Comment by JakeGinnivan** [comment]
Related to https://github.com/joyent/node/issues/2318 by the looks

**Comment by JakeGinnivan** [comment]
Fixed by changing the command to `onchange foo.js -- jshint.cmd foo.js`

**Comment by mattecapu** [comment]
@JakeGinnivan yay, you found the problem!
While the folks at Joyent solve the bug, we could switch to [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn)
It claims to solve `child_process.spawn` problems (including the ignoring of PATHEXT that causes our issue).
As soon as I have some time to test it (not before sunday, unfortunately), I can make a pull request.
