### ISSUE TITLE
How to detect hidden files change?

### ISSUE THREAD

**Issue by mifi** [Qard/onchange#85]
File named `.hidden`

**Comment by blakeembrey** [comment]
Possibly https://github.com/paulmillr/chokidar/issues/577#issuecomment-278147894, but I suspect there's not enough hooks exposed to do this better. We can add something to support you if you want to contribute.

**Comment by blakeembrey** [comment]
Looks like this was possibly resolved in chokidar 3.1 according to https://github.com/paulmillr/chokidar#changelog.
