### ISSUE TITLE
Chokidar 3.0 is out with massive improvements

### ISSUE THREAD

**Issue by ferhatelmas** [Qard/onchange#88]
> Massive CPU & RAM consumption improvements. 17x package & deps size reduction. Node 8+-only

https://github.com/paulmillr/chokidar/releases/tag/3.0.0

**Comment by blakeembrey** [comment]
I’m aware, thanks! https://github.com/Qard/onchange/pull/87

I just haven’t cut a new major release yet. I’ll try and get to it this week.

**Comment by ferhatelmas** [comment]
Thanks, looking forward to it.

**Comment by blakeembrey** [comment]
Merged with https://github.com/Qard/onchange/pull/87.
