### ISSUE TITLE
Time stamp in console log output

### ISSUE THREAD

**Issue by jannavratil** [Qard/onchange#9]
Hi, 
did you plan add time stamp to log output? Could be via some argument.
For example: 
```
changed /some/file/path/changedFile.js

> SOME TASK
```
will be 

```
[01-19-15 11:11:27]
changed /some/file/path/changedFile.js

> SOME TASK
```

Did you plan this or semothing similar?
Thanks for answer.

**Comment by Qard** [comment]
I went the other direction entirely and hid logging behind a `DEBUG=onchange` environment variable via [debug](https://npmjs.org/package/debug). I don't think I'll add timestamps to that. You can simply add timestamps to your change script, if you really want it. In bash, it's just `date +%s`.
