### ISSUE TITLE
[FEATURE REQUEST] Support for '--ignore-path' flag as ​​eslint and prettier

### ISSUE THREAD

**Issue by vinyfc93** [Qard/onchange#93]
Hi guys!

I would like to have the '--ignore-path' flag to ignore files as I do with eslint and prettier. 
Given a folder structure like:
```bash
$ tree -a
.
├── .gitignore
├── LICENSE.md
├── README.md
├── dist
│   └── chunk.main.js
├── index.js
├── package-lock.json
├── package.json
├── server.log
└── src
    ├── auth.js
    └── utils.js
```
We would have:
``` bash
# like
$ prettier '**/*. js' --ignore-path .gitignore

# and
$ eslint --ext  .js, .json, .html --ignore-path .gitignore . 


# it could be
$ onchange '**/*{.js,.html,.yml,.json,.md}' --ignore-path .gitignore -- prettier --write {{change}}

# and
$ onchange '**/*{.js,.html,.json}' --ignore-path .gitignore -- eslint --fix {{change}}
```
I don't know if this is possible or interesting for you, but I like this approach, and I'm willing to work on it if you think it's a good idea.

What do you say?

**Comment by blakeembrey** [comment]
Have you tried the exclude flag?

**Comment by vinyfc93** [comment]
@blakeembrey, yes! I Tried.

**Comment by vinyfc93** [comment]
Maybe I wasn't clear ...

The sample folder structure was just to show what .gitignore would be called.

My actual use case is a big monorepo I'm working on. I have to ignore several different paths that, perhaps not coincidentally, match the files in my .gitignore.

Let's go to a new example:

``` bash
# I have to ignore, folder **/.Clinic,  folder ./models/**  but not *.proto file, folder ./lib, and * .json files in src folder
onchange '**/*{.js,.html,.yml,.json,.md}' -e '**/{node_modules,.clinic}/**' -e './lib' -e './models/*{.js,.ts,.grahql} '-e' src/*.json ' -- prettier --write {{change}}
```

I have to edit the '-e' flag whenever I do something that changes the ignore requirement. If my .gitignore file or a custom ignore file were read as part of my ignore files this could at least just ignore it changing everything in one place for linter, formatter and onchange.

The purpose of the functionality is to allow a more accurate and safe ignition.

What do you say?

**Comment by blakeembrey** [comment]
That makes more sense. Happy to accept a PR for it, it should reuse whatever functionality the other modules have built out.

**Comment by vinyfc93** [comment]
Done! Looking forward to the feedback.
