### ISSUE TITLE
Could npm ERR logs be prevented when the command has warnings

### ISSUE THREAD

**Issue by ovanderzee** [Qard/onchange#96]
I use onchange to run eslint and then build my plugin on saving sources. When eslint finds errors, I get logs like these: 

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! openrgb@1.1.0 build: `eslint src/rgb.js && terser src/rgb.js --source-map --output dist/openrgb.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the openrgb@1.1.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/ovdz/.npm/_logs/2019-10-04T11_56_21_623Z-debug.log

I dont't need such logs, eslint is clear enough and does cause such output. When ran using npx, i don't see these logs. Is it possible to use onchange without these logs?

My package.json contains: 

    "scripts": {
      "build": "eslint src/rgb.js && terser src/rgb.js --source-map --output dist/openseadragonrgb.js",
      "watch": "onchange --initial \"src/*.js\" -- npm run build"
    },
    ...
    "devDependencies": {
      "eslint": "^6.5.1",
      "onchange": "^6.1.0",
      "terser": "^4.3.4"
    }

**Comment by blakeembrey** [comment]
This is an NPM feature, you can always disable it with the “silent” flag: https://docs.npmjs.com/cli/run-script
